### ISSUE TITLE
Inconsistent base for derived file names within an acquisition

### ISSUE THREAD

**Issue by mfaytak** [rsprouse/ultratils#4]
**Main issue**
Putting this up here so we can discuss it later. The base name that file names within an acquisition are built off of is not consistent between the EchoB session (which is not actually in the repo yet) and the Ultrasonix session. Both are built off the acquisition timestamp, but Ultrasonix has an additional .bpr extension where EchoB simply attaches .wav to the timestamp. That is:

- WAV files are named (timestamp).bpr.wav when they are acquired through ultrasession.py
- WAV files are named (timestamp).wav when they are acquired through the EchoB session, and not, say, (timestamp).raw.wav

This has created some headaches for me in processing before, since Ultrasonix processing scripts don't work on EchoB experiments and vice versa. 

**psync**
This is also indirectly responsible for file naming problems in psync, where files called (timestamp).bpr and (timestamp).bpr.wav need to exist for --seek mode to work (but not in single-file mode). If called on EchoB-style files with no extra ".raw" in the filename, psync may not work due to files named (timestamp).raw.* not existing. I made a commit on my fork to address this before realizing that the issue is not in psync, per se - see comments in my ultratils/scripts/psync, lines 167-170.

**Comment by rsprouse** [comment]
It became apparent in writing acquistion code for the EchoB that including .bpr in the audio filename was a mistake at the outset, and the right thing to do going forward is to stop doing that.

The fix itself is fairly simple, but it could cause headaches for those who are working with existing acquisitions that have the extraneous .bpr.wav. A way to stay backwards-compatible will be to put access to .wav files (without .bpr) in a try block and to try again with .bpr.wav if the first try fails.
